### ISSUE TITLE
Incompatible version - 1.21.1

### ISSUE THREAD

**Issue by wolfie-cz** [whiteh4cker-tr/Seasons#1]
The plugin is not working. Every 2 seconds there is repeating Error.
I tried this plugin on pure (clean, no other plugins ) Paper and Purpur servers (1.21.1) on crafty controller. 

[17:51:50 WARN]: [Seasons] Task #42 for Seasons v1.0.0 generated an exception
java.lang.IncompatibleClassChangeError: Found class org.bukkit.block.Biome, but interface was expected
	at Seasons-1.0.0.jar/tr.alperendemir.seasons.temperature.modifier.BiomeTemperatureModifier.modifyTemperature(BiomeTemperatureModifier.java:14) ~[Seasons-1.0.0.jar:?]
	at Seasons-1.0.0.jar/tr.alperendemir.seasons.temperature.TemperatureCalculator.calculateTemperature(TemperatureCalculator.java:37) ~[Seasons-1.0.0.jar:?]
	at Seasons-1.0.0.jar/tr.alperendemir.seasons.player.PlayerManager.updateTemperatures(PlayerManager.java:52) ~[Seasons-1.0.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1770) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by whiteh4cker-tr** [comment]
Hi, I confirmed that the plugin is not compatible with 1.21.1. Please use Spigot or Paper version 1.21.4 and check back in.
