### ISSUE TITLE
在purpur端服务器使用时遇到了这个问题

### ISSUE THREAD

**Issue by CoArrayLiu** [whiteh4cker-tr/Seasons#2]
[22:30:17 ERROR]: Could not pass event ChunkLoadEvent to Seasons v1.0.3
java.lang.IllegalArgumentException: y out of range (expected 0-255, got -1)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.CraftChunk.validateChunkCoordinates(CraftChunk.java:432) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.craftbukkit.CraftChunk.getBlock(CraftChunk.java:118) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at Seasons-1.0.3.jar/tr.alperendemir.seasons.effects.SummerEffects.spawnBerryBushes(SummerEffects.java:144) ~[Seasons-1.0.3.jar:?]
        at Seasons-1.0.3.jar/tr.alperendemir.seasons.effects.SummerEffects.onChunkLoad(SummerEffects.java:87) ~[Seasons-1.0.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:704) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at ca.spottedleaf.moonrise.common.util.ChunkSystem.onChunkBorder(ChunkSystem.java:103) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1276) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1391) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1375) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1322) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:414) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:866) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:410) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:386) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:407) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:351) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:846) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:815) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1923) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1370) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by whiteh4cker-tr** [comment]
0359b2c
